apiVersion: apps/v1
kind: Deployment
metadata:
  name: constellation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: constellation
  template:
    metadata:
      labels:
        app: constellation
    spec:
      containers:
      - name: constellation
        image: docker.io/library/constellation:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8080"
